### ISSUE TITLE
Log In/ Sign Up not working

### ISSUE THREAD

**Issue by Rofelix** [O-C-R/floodwatch-issue-tracking#16]
Hello Floodwatch team,

unfortunately I can't log in to your extension. It worked for a month and now it just stopped.
Other users have the same issue. Please fix it as soon as possible.

Best,  

Robin

**Comment by ElleryR** [comment]
Hi Robin,

I just wrote you back on our support email. There was a server issue that should be fixed now. Please let me know if you have any continuing issues.

Thanks,

Ellery
