### ISSUE TITLE
"Help us tag this ad!" not working

### ISSUE THREAD

**Issue by ElleryR** [O-C-R/floodwatch-issue-tracking#2]
User reported - 

"Help us tag this ad!" does not let me tag the ad somehow

Waiting back for more details as to OS and version of Chrome.

**Comment by ElleryR** [comment]
System info: 

Google Chrome   38.0.2125.101 (Official Build 290379) beta
OS  Mac OS X 
Blink   537.36 (@183011)
JavaScript  V8 3.28.71.15
Flash   15.0.0.152
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36

No errors on console log

**Comment by iaaaan** [comment]
"does not let me tag the ad somehow" 
Does this mean the tagging screen doesn't appear (nothing happens when clicking on "help us tag this ad" button), or does this mean the tagging screen works improperly?

Thanks!

**Comment by ElleryR** [comment]
Let me check with the person that reported it! I assumed that it meant
nothing happens when clicking on it (he included a screenshot that was just
of the "Help us tag this ad" label, but I'll double check.

**Comment by ElleryR** [comment]
Jer is seeing this as well - on clicking both "Help us tag this ad" and "Edit ad tagging" nothing happens on clicking the buttons.
