### ISSUE TITLE
When logged off, login page pops up at an annoying frequence

### ISSUE THREAD

**Issue by iaaaan** [O-C-R/floodwatch-issue-tracking#7]
If for some reason he user wants/needs to stay logged off for a while, the login page shouldn't popup everytime the extension tries to capture an ad.

We could have the following instead:
Only when launching chrome (once a day max?), display a popup notification coming form floodwatch's icon with a message explaining no ad is being collected since the user has logged off.

**Comment by ElleryR** [comment]
Let's have a discussion around this - If for whatever reason people want to remain logged out, wouldn't it make more sense just to direct them to temporarily disable the plugin?  

Otherwise, maybe we can time it to be once every few hours? Just don't want a situation where someone closes the tab and then forgot that it was ever open.....

**Comment by iaaaan** [comment]
IMHO a simple chrome notification (like this http://4.bp.blogspot.com/-U1SSfrl5uZ8/TrLd3L_jN0I/AAAAAAAA7Tc/EyLGg7nT4Q4/s640/google-plus-notifications-extension.png) on Chrome launch would be enough, and much less intrusive than a tab that pops up out of nowhere. Also I suspect people won't read what we might tell them in that login tab. My friend didn't and came at me saying "ian, wth does floodwatch pops up pages every 5 minutes?". I wouldn't blame her for that: when something pops up my first reaction is to close it.

**Comment by blprnt** [comment]
What does Ghostery do? Or lightbeam?

I know for most plugins that require login (ie. Evernote) it never asks you again after the initial login.

I understand there are privacy implications here, but it definitely shouldn’t be annoying people! I’d say that this is fairly high priority to fix…

-J

**Comment by ElleryR** [comment]
Let's check other models for examples, but I think in our case it's been overwritten a couple of times for people because we're pushing new versions. Otherwise it doesn't prompt once you've logged in. Agree with Ian that a chrome notification would be less intrusive however

**Comment by iaaaan** [comment]
As far as I know Ghostery and Lightbeam don't require login. Other services such as Evernote or Icebergs are a different case because users actively ask them to bookmark one thing or another: they only need to ask users for their info when they are interacting with the extension.

As Ellery is saying, this issue only occurs for someone who logged off. So we can assume it's a very limited number of users for now.

**Comment by ElleryR** [comment]
Improved in the latest version - let's wait for feedback and then do another round of development on this.
